name: Elixir CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  MIX_ENV: test

jobs:
  mix_test:
    name: mix test (Elixir ${{matrix.elixir}} | OTP ${{matrix.otp}})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: "1.12.x"
            otp: 24
          - elixir: "1.13.x"
            otp: 25.1
          - elixir: "1.14.x"
            otp: 25.1
          - elixir: "1.15.x"
            otp: 26.0
          - elixir: "1.16.x"
            otp: 26.2
          - elixir: "1.17.x"
            otp: 27
          - elixir: "1.18.x"
            otp: 27

    steps:
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test

      - name: Hex Audit
        run: mix hex.audit

      - name: Check Formatting
        if: ${{ matrix.elixir == '1.16.x' }} # we only care about formatting for latest version of Elixir
        run: mix format --check-formatted

      - name: Compiles w/o Warnings
        if: ${{ matrix.elixir == '1.16.x' }} # we only care about warnings for latest version of Elixir
        run: mix compile --warnings-as-errors

      - name: Credo
        run: mix credo --all --strict

      - name: Run Tests
        run: mix test
